const USER_LOADED = "USER_LOADED";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const AUTH_ERROR = "AUTH_ERROR";
const LOGOUT = "LOGOUT";
const UPDATE_USER = "UPDATE_USER";

export {
  USER_LOADED,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  AUTH_ERROR,
  LOGOUT,
  UPDATE_USER,
};
