const CREATE_PARTNER = "CREATE_PARTNER";
const CREATE_PARTNER_ERROR = "CREATE_PARTNER_ERROR";
const UPDATE_PARTNER = "UPDATE_PARTNER";
const UPDATE_PARTNER_ERROR = "UPDATE_PARTNER_ERROR";
const UPDATE_SETTINGS = "UPDATE_SETTINGS";
const UPDATE_SETTINGS_ERROR = "UPDATE_SETTINGS_ERROR";
const GET_PARTNERS = "GET_PARTNERS";
const GET_PARTNER_ERROR = "GET_PARTNER_ERROR";
const SETUP_PARTNER = "SETUP_PARTNER";
const SETUP_PARTNER_ERROR = "SETUP_PARTNER_ERROR";
const GET_SAMPLES = "GET_SAMPLES";
const GET_SAMPLES_ERROR = "GET_SAMPLES_ERROR";
const CREATE_SAMPLE = "CREATE_SAMPLE";
const CREATE_SAMPLE_ERROR = "CREATE_SAMPLE_ERROR";
const UPDATE_SAMPLE = "UPDATE_SAMPLE";
const UPDATE_SAMPLE_ERROR = "UPDATE_SAMPLE_ERROR";
const GET_REPORT_TYPES = "GET_REPORT_TYPES";
const GET_REPORT_TYPES_ERROR = "GET_REPORT_TYPES_ERROR";
const GET_SHIPMENT = "GET_SHIPMENT";
const GET_SHIPMENT_ERROR = "GET_SHIPMENT_ERROR";
const CREATE_SHIPMENT = "CREATE_SHIPMENT";
const CREATE_SHIPMENT_ERROR = "CREATE_SHIPMENT_ERROR";
const SET_SHIPMENT_STATUS = "SET_SHIPMENT_STATUS";
const SET_SHIPMENT_STATUS_ERROR = "SET_SHIPMENT_STATUS_ERROR";
const DELETE_SAMPLE = "DELETE_SAMPLE";
const DELETE_SAMPLE_ERROR = "DELETE_SAMPLE_ERROR";
const RESET = "RESET";
const SAVE_KIT_REQUEST = "SAVE_KIT_REQUEST";
const SAVE_KIT_REQUEST_ERROR = "SAVE_KIT_REQUEST_ERROR";
const GET_REQUESTED_KITS = "GET_REQUESTED_KITS";
const GET_KITS_ERROR = "GET_KITS_ERROR";
const UPDATE_KIT_REQUEST = "UPDATE_KIT_REQUEST";
const UPDATE_KIT_REQUEST_ERROR = "UPDATE_KIT_REQUEST_ERROR";

export {
  CREATE_PARTNER,
  CREATE_PARTNER_ERROR,
  UPDATE_PARTNER,
  UPDATE_PARTNER_ERROR,
  UPDATE_SETTINGS,
  UPDATE_SETTINGS_ERROR,
  GET_PARTNERS,
  GET_PARTNER_ERROR,
  SETUP_PARTNER,
  SETUP_PARTNER_ERROR,
  GET_SAMPLES,
  GET_SAMPLES_ERROR,
  CREATE_SAMPLE,
  CREATE_SAMPLE_ERROR,
  UPDATE_SAMPLE,
  UPDATE_SAMPLE_ERROR,
  GET_REPORT_TYPES,
  GET_REPORT_TYPES_ERROR,
  GET_SHIPMENT,
  GET_SHIPMENT_ERROR,
  CREATE_SHIPMENT,
  CREATE_SHIPMENT_ERROR,
  SET_SHIPMENT_STATUS,
  SET_SHIPMENT_STATUS_ERROR,
  DELETE_SAMPLE,
  DELETE_SAMPLE_ERROR,
  RESET,
  SAVE_KIT_REQUEST,
  SAVE_KIT_REQUEST_ERROR,
  GET_REQUESTED_KITS,
  GET_KITS_ERROR,
  UPDATE_KIT_REQUEST,
  UPDATE_KIT_REQUEST_ERROR,
};
