const ADD_ITEM = "ADD_ITEM";
const ADD_ITEM_ERROR = "ADD_ITEM_ERROR";
const UPDATE_ITEM = "UPDATE_ITEM";
const UPDATE_ITEM_ERROR = "UPDATE_ITEM_ERROR";
const GET_PARTNERS = "GET_PARTNERS";
const GET_PARTNER_ERROR = "GET_PARTNER_ERROR";
const RESET = "RESET";
export {
  ADD_ITEM,
  ADD_ITEM_ERROR,
  UPDATE_ITEM,
  UPDATE_ITEM_ERROR, 
  GET_PARTNERS,
  GET_PARTNER_ERROR,  
  RESET,
};
